tag: rtu_rtrl
wandb_project_name: debugging
exp_seed: 0

#### Env related
env_config:
  domain: brax  # gymnax, brax,pobrax_p or pobrax_v, popjax
  env_name: ant
  ## for env with continuous action space
  continous_a: True
  clip_action: True
  ## wrappers
  normalize_obs: True
  normalize_reward: True
  ## for creating partial obs in gymnax env
  masked_obs: False
  add_noise: false
  add_reward_prev_action: False # currently works with discrete action space


#### ppo related
ppo_config:
  gamma: 0.99
  gae_lambda: 0.95

  total_steps: 2000000
  rollout_steps: 2048

  epochs: 4
  num_mini_batch: 32
  seq_len_in_minibatch: 1 # 1 for no rnn or rtrl

  clip_eps: 0.2
  vf_coef: 0.5
  gradient_clipping: False
  max_grad_norm: 0.5
  entropy_coef: 0.0

  ## network related
  lr: 0.0001
  rec_fn: mlp
  d_rec: None
  activation: tanh
  d_shared_repr: [64]
  d_actor_head: 64
  d_critic_head: 64

  # ablation specific
  stale_target:  true
  stale_gradient: true
  grad_estimator: bp    # bp with mlps. with rnns use bptt, rtrl or rtrl_bptt
